//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMonitorWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class alert_history
    {
        public alert_history()
        {
            this.alerts = new HashSet<alert>();
        }
    
        public string id_histo_alert { get; set; }
        public Nullable<int> id_warning { get; set; }
        public Nullable<System.DateTime> begin_date_task { get; set; }
        public Nullable<System.DateTime> end_date_task { get; set; }
    
        public virtual ICollection<alert> alerts { get; set; }
    }
}
