//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMonitorWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class exec_tasks
    {
        public string id_exe_task { get; set; }
        public string id_check { get; set; }
        public string id_task { get; set; }
        public string exe_order { get; set; }
        public string checker_id_checker { get; set; }
        public string tasks_history_id_histo_task { get; set; }
    
        public virtual checker checker { get; set; }
        public virtual tasks_history tasks_history { get; set; }
        public virtual alert alert { get; set; }
    }
}
