//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMonitorWebApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HAMonitorEntities : DbContext
    {
        public HAMonitorEntities()
            : base("name=HAMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alert> alerts { get; set; }
        public virtual DbSet<checker> checkers { get; set; }
        public virtual DbSet<exec_tasks> exec_tasks { get; set; }
        public virtual DbSet<hardware> hardwares { get; set; }
        public virtual DbSet<task_type> task_type { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<tasks_history> tasks_history { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<alert_history> alert_history { get; set; }
    }
}
