//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMonitorWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class hardware
    {
        public hardware()
        {
            this.tasks = new HashSet<task>();
        }
    
        public string id_hard { get; set; }
        public string categories { get; set; }
        public string description { get; set; }
        public string ip_adress { get; set; }
        public string mac_adress { get; set; }
    
        public virtual ICollection<task> tasks { get; set; }
    }
}
