//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMonitorWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks_history
    {
        public tasks_history()
        {
            this.exec_tasks = new HashSet<exec_tasks>();
        }
    
        public string id_histo_task { get; set; }
        public Nullable<int> result_task { get; set; }
        public Nullable<System.DateTime> begin_date_task { get; set; }
        public Nullable<System.DateTime> end_date_task { get; set; }
    
        public virtual ICollection<exec_tasks> exec_tasks { get; set; }
    }
}
