//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMonitorWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_type
    {
        public string id { get; set; }
        public string param { get; set; }
        public string path { get; set; }
    
        public virtual task task { get; set; }
    }
}
