//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMonitorWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public task()
        {
            this.hardwares = new HashSet<hardware>();
        }
    
        public string id_task { get; set; }
        public string id_type { get; set; }
        public string id_hardware { get; set; }
        public string description { get; set; }
        public string checker_id_checker { get; set; }
    
        public virtual checker checker { get; set; }
        public virtual ICollection<hardware> hardwares { get; set; }
        public virtual task_type task_type { get; set; }
    }
}
