//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAMonitorWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.checkers = new HashSet<checker>();
        }
    
        public string id_user { get; set; }
        public string role { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<checker> checkers { get; set; }
    }
}
